apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
commonLabels:
  app: jignesh-panchal-buildah
  app.kubernetes.io/instance: jignesh-panchal-buildah-instance
  app.kubernetes.io/name: jignesh-panchal-buildah
images:
- name: quay.io/upslope/express-sample-app
  newName: quay.io/repository/jigneshkvp/express-assignment-app
  newTag: 1f4f64c5f5de06561abd5f97828eab66207b7f4c
